export const API_ENDPOINTS = {
  REGISTER: "/auth/register",
  LOGIN: "/auth/login",
  CATEGORIES: "/store/categories",
  PRODUCTS: "/store/products",
  PRODUCT_DETAILS: (id) => `/store/products/${id}`,
  HOMEPAGE: "/store/cms/homepage",
  NEWSLETTER_SUBSCRIBE: "/store/cms/newsletter/subscribe",
  ADD_TO_CART: (id) => `/customer/cart/add/${id}`,
  GET_CART: "/customer/cart",
  REMOVE_CART: (id) => `/customer/cart/remove/${id}`,
  GET_ADDRESSES: "/customer/addresses",
  CREATE_ADDRESS: "/customer/addresses",
  GET_ADDRESS: `/customer/addresses/{address_id}`,
  UPDATE_ADDRESS: `/customer/addresses/{address_id}`,
  DELETE_ADDRESS: `/customer/addresses/{address_id}`,
  GET_ORDERS: `/customer/orders`,
  GET_ORDERBYID: `/customer/orders/{order_id}`,
  TRACK_ORDER: (orderId) => `/customer/orders/${orderId}/tracking`,
  CREATE_REVIEW: `/customer/reviews`,
  PAYMENT: `/customer/orders/payment-success`,
  CREATE_ORDER: "/customer/orders",
  CART_SUMMERY: "/customer/cart/summary",
  APPLY_COUPON: "/customer/cart/apply-coupon",
  WISHLIST: "/customer/wishlist",
  WISHLIST_ITEM: (productId) => `/customer/wishlist/${productId}`,
  CREATE_RAZORPAY_PAYMENT: "/billing/create-payment",
  VERIFY_RAZORPAY_PAYMENT: "/billing/verify-payment",
};
